name: 'Triage: add issue/PR to project'

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

jobs:
  add-to-triage-project:
    name: Add to triage project
    runs-on: ubuntu-latest
    steps:
      - name: Is Organization Member
        uses: JamesSingleton/is-organization-member@1.0.0
        with:
          organization: nagash77-cypress
          username: ${{ github.event.issue.user.login }}
          token: ${{ secrets.ADD_TO_PROJECT_TOKEN}}
      - name: Add issue from non-member to Triage Board
        if: steps.is_organization_member.outputs.result == false
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/nagash77-cypress/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
        
          
